"""empty message

Revision ID: 1506bc5fdcb3
Revises: 5a12360af745
Create Date: 2015-12-16 10:15:00.989000

"""

# revision identifiers, used by Alembic.
revision = '1506bc5fdcb3'
down_revision = '5a12360af745'

from alembic import op
import sqlalchemy as sa
import models


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('access_key', models.CoerceUTF8(length=100), nullable=False))
    op.add_column('users', sa.Column('access_token', models.CoerceUTF8(length=100), nullable=False))
    op.add_column('users', sa.Column('active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('creation_date', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('employee', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('id_site', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('profile_link', models.CoerceUTF8(length=500), nullable=False))
    op.add_column('users', sa.Column('registration_date', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('token_expires', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('website', models.CoerceUTF8(length=500), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'website')
    op.drop_column('users', 'token_expires')
    op.drop_column('users', 'registration_date')
    op.drop_column('users', 'profile_link')
    op.drop_column('users', 'id_site')
    op.drop_column('users', 'employee')
    op.drop_column('users', 'creation_date')
    op.drop_column('users', 'active')
    op.drop_column('users', 'access_token')
    op.drop_column('users', 'access_key')
    ### end Alembic commands ###
