"""empty message

Revision ID: 16b749a93455
Revises: None
Create Date: 2015-12-16 10:57:45.911000

"""

# revision identifiers, used by Alembic.
revision = '16b749a93455'
down_revision = None

from alembic import op
import sqlalchemy as sa
import models


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('name', models.CoerceUTF8(length=125), nullable=False),
    sa.Column('value', models.CoerceUTF8(length=500), nullable=False),
    sa.Column('user_manage', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', models.CoerceUTF8(length=100), nullable=False),
    sa.Column('employee', sa.Boolean(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('registration_date', sa.DateTime(), nullable=False),
    sa.Column('id_site', sa.BigInteger(), nullable=True),
    sa.Column('website', models.CoerceUTF8(length=500), nullable=False),
    sa.Column('profile_link', models.CoerceUTF8(length=500), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('token_expires', sa.DateTime(), nullable=False),
    sa.Column('access_token', models.CoerceUTF8(length=100), nullable=False),
    sa.Column('access_key', models.CoerceUTF8(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('settings')
    ### end Alembic commands ###
