"""empty message

Revision ID: 188ac33a7db0
Revises: 3d8a695151f7
Create Date: 2015-12-17 13:34:07.478000

"""

# revision identifiers, used by Alembic.
revision = '188ac33a7db0'
down_revision = '3d8a695151f7'

from alembic import op
import sqlalchemy as sa
import models


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'access_key')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('access_key', sa.VARCHAR(length=100), nullable=False))
    ### end Alembic commands ###
