"""empty message

Revision ID: 3d8a695151f7
Revises: 36728651098b
Create Date: 2015-12-16 23:16:23.990000

"""

# revision identifiers, used by Alembic.
revision = '3d8a695151f7'
down_revision = '36728651098b'

from alembic import op
import sqlalchemy as sa
import models


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    ### end Alembic commands ###
